name : Pipeline para revisar archivo

on:
    push:
        branches : ["main"]

jobs:
    build:
        runs-on : ubuntu-latest

        steps:
            
            - name: Verificar si app.js existe
              run: |
                if [ -f "$GITHUB_WORKSPACE/app.js" ]; then
                    echo "✅ El archivo app.js existe en la raíz."
                else
                    echo "❌ El archivo app.js no existe en la raíz."
                    echo "Archivos encontrados en la raíz:"
                    ls -la "$GITHUB_WORKSPACE"
                    exit 1
                fi

            - name: Checkout del código
              uses: actions/checkout@v4

            - name: Usar NODE JS
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            
            - name: Construir app con node
              run: npm install 
